/*
* 
* 
*
*
*/

proc iml;

start calculatePowerShieh(ALPHA,N,KSTAR,B,C,U,SIGMA);

CMAT={0 1 0 0, 0 0 1 0, 0 0 0 1};
AMAT=({-1,0,1}/SQRT(2))||({1,-2,1}/SQRT(6));
R=NROW(B);P=NCOL(B);C=NROW(CMAT);A=NCOL(AMAT);S=MIN(A,C);CA=C#A;
SMALLN=N-R;
EPM=(AMAT 	*SIGMA*AMAT);
HPM=(CMAT*B*AMAT) 	*INV(CMAT*INV(KSTAR)*CMAT 	)*(CMAT*B*AMAT);
EIHPM=INV(EPM)*HPM;
*L;
IF CA <4 THEN T=1;ELSE T=SQRT((CA##2-4)/(C##2+A##2-5));
DF2L=T#(SMALLN-(A-C+1)/2)-(CA-2)/2;
FCRITL=FINV(1-ALPHA,CA,DF2L,0);
g. shieh 357
LPM=DET(INV(I(A)+EIHPM));EFSL=T#(LPM##(-1/T)-1);
POWERL=1-PROBF(FCRITL,CA,DF2L,N#EFSL);
*V;
DF2V=S#(SMALLN+S-A);
FCRITV=FINV(1-ALPHA,CA,DF2V,0);
VPM=TRACE(EIHPM*INV(I(A)+EIHPM));EFSV=S#VPM/(S-VPM);
POWERV=1-PROBF(FCRITV,CA,DF2V,N#EFSV);
*T1;
DF2T1=S#(SMALLN-A-1)+2;
FCRITT1=FINV(1-ALPHA,CA,DF2T1,0);
T1PM=TRACE(EIHPM);EFST1=T1PM;
POWERT1=1-PROBF(FCRITT1,CA,DF2T1,N#EFST1);
*T2;
G=(SMALLN##2-SMALLN#(2#A+3)+A#(A+3))/
(SMALLN#(C+A+1)-(C+2#A+A##2-1));
DF2T2=4+(CA+2)#G;
FCRITT2=FINV(1-ALPHA,CA,DF2T2,0);
T2PM=TRACE(EIHPM);EFST2=T2PM;
POWERT2=1-PROBF(FCRITT2,CA,DF2T2,N#EFST2);
PRINT N[FORMAT=6.0],
EFSL[FORMAT=7.4] EFSV[FORMAT=7.4] EFST1[FORMAT=7.4]
EFST2[FORMAT=7.4],
POWERL[FORMAT=7.4] POWERV[FORMAT=7.4] POWERT1[FORMAT=7.4]
POWERT2[FORMAT=7.4];








finish;
store module=calculatePowerShieh;

run;
